openapi: 3.0.1
info:
  title: FSL
  description: Fascicolo Sociale e Lavorativo del Cittadino
  contact:
    name: DG Innovazione
    email: dginnovazionediv3@lavoro.gov.it
  version: 1.0.0
  x-summary: Fascicolo Sociale e Lavorativo del Cittadino
  x-semantic-score: 0.5
  x-semantic-score-timestamp: 1775577038231
servers:
  - url: https://apimlpstest.lavoro.gov.it/rest
    description: FSL Test Environment
  - url: https://apimlps.lavoro.gov.it/rest
    description: FSL Production Environment
paths:
  /fsl/areasociale/v1/patto:
    post:
      tags:
        - Gepi
      summary: Consultazione dettaglio versione PaiS
      description: Dato l'identificativo del Caso in gestione agli assistenti sociali per la definizione del Patto per l’Inclusione Sociale (PaIS) e la relativa versione di interesse, il servizio restituisce le relative informazioni di dettaglio
      operationId: ConsultazioneDettaglioPaiS
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FSL.Api.Domain.Models.Gepi.ConsultazioneDettaglioPaiS.ConsultazioneDettaglioPaiS_Input'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FSL.Api.Domain.Models.Gepi.ConsultazioneDettaglioPaiS.ConsultazioneDettaglioPaiS_Output'
        '400':
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ProblemDetails'
        '401':
          description: Unauthorized
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ProblemDetails'
        '403':
          description: Forbidden
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ProblemDetails'
        '404':
          description: Not Found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ProblemDetails'
        '500':
          description: Internal Server Error
  /status:
    get:
      tags:
        - Health Check API
      description: Returns the health status of this service
      operationId: HealthCheckStatus
      responses:
        '200':
          description: API service is healthy
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/FSL.Common.Support.Models.Api.HealthCheckSuccess'
        '403':
          description: Forbidden
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ProblemDetails'
        '500':
          description: Internal Server Error
        '503':
          description: API service is not healthy
components:
  schemas:
    FSL.Api.Domain.Models.Gepi.ConsultazioneDettaglioPaiS.ConsultazioneDettaglioPaiS_Input:
      required:
        - cFOperatore
        - identificativo
        - modalitaAccesso
        - nVersione
      type: object
      properties:
        codiceATS:
          type: string
          nullable: true
        comuni:
          type: array
          items:
            type: string
          nullable: true
        modalitaAccesso:
          type: integer
          format: int32
        cFOperatore:
          minLength: 1
          type: string
        identificativo:
          minLength: 1
          type: string
        nVersione:
          type: integer
          format: int32
      additionalProperties: false
    FSL.Api.Domain.Models.Gepi.ConsultazioneDettaglioPaiS.ConsultazioneDettaglioPaiS_Output:
      required:
        - data
        - esito
      type: object
      properties:
        esito:
          $ref: '#/components/schemas/FSL.Api.Domain.Models.Gepi.Esito'
        data:
          $ref: '#/components/schemas/FSL.Api.Domain.Models.Gepi.ConsultazioneDettaglioPaiS.Data'
      additionalProperties: false

    FSL.Api.Domain.Models.Gepi.ConsultazioneDettaglioPaiS.Data:
      type: object
      properties:
        identificativo:
          type: string
        versioneRDC:
          type: boolean
        nVersione:
          type: integer
          format: int32
        stato:
          type: string
        istatComune:
          type: string
        codiceATS:
          type: string
        caseManager:
          type: string
          nullable: true
        dataFinalizzazione:
          type: string
          nullable: true
        dataFirma:
          type: string
          nullable: true
        obiettiviRisultati:
          type: array
          items:
            $ref: '#/components/schemas/FSL.Api.Domain.Models.Gepi.ConsultazioneDettaglioPaiS.ObiettivoRisultato'
        impegni:
          type: array
          items:
            $ref: '#/components/schemas/FSL.Api.Domain.Models.Gepi.ConsultazioneDettaglioPaiS.Impegno'
        sostegni:
          type: array
          items:
            $ref: '#/components/schemas/FSL.Api.Domain.Models.Gepi.ConsultazioneDettaglioPaiS.Sostegno'
      additionalProperties: false
      x-jsonld-type: https://w3id.org/italia/labour-social-policies/onto/social/PattoInclusioneSocialeDelCaso
      x-jsonld-context:
        "@vocab": https://w3id.org/italia/labour-social-policies/onto/social/
        identificativo: https://w3id.org/italia/labour-social-policies/onto/core/identificativoAtto
        versioneRDC: versioneRDC
        nVersione: versionePaIS
        stato: statusPaIS
        istatComune:
          '@id': https://w3id.org/italia/onto/CLV/hasCity
          '@context':
              label: http://www.w3.org/2000/01/rdf-schema#label
        codiceATS:
          '@id': https://w3id.org/italia/labour-social-policies/onto/core/appartieneAdAmbitoTerritoriale
          '@type': '@id'
          '@context':
              "@base": 'https://w3id.org/italia/labour-social-policies/controlled-vocabulary/data/tipo_ambito_territoriale/'
              id: '@id'
        caseManager: https://w3id.org/italia/onto/CPV/taxCode
        dataFinalizzazione: dataFinalizzazioneAnalisiPreliminare
        dataFirma: dataFirmaPaIS
        obiettiviRisultati:
          '@id': haObiettivoPaIS
        impegni:
          '@id': haImpegnoPaIS
        sostegni:
          '@id': haSostegnoPaIS
      example:
        identificativo: GEPI-20250101-1
        versioneRDC: False
        nVersione: 1
        stato: 'Finalizzato'
        istatComune: '058091'
        codiceATS: '5-202004142240267'
        caseManager: "AAAAAA00A00A000A"
        dataFinalizzazione: '2025-07-12'
        dataFirma: '2025-05-14'
        obiettiviRisultati:
          - descrizioneObiettivo: 'Sostenere l’educazione e la formazione degli adulti'
            idObiettivo: 'ba16de1c-f5a0-4144-90d5-15c354e9eff3'
        impegni:
          - tipologia: 'Tipologia Test'
            dataAvvio: '2025-01-01'
            datafine: '2025-06-30'
            nucleo:
              - 'AAAAAA00A00A000A'
        sostegni:
          - tipologia: 'Formazione per il conseguimento di Qualifiche professionali'
            idTipologia: 'bcc888fd-00c7-43ef-8edb-e2bc9b147d17'
            codiceFiscale: 'AAAAAA00A00A000A'
            dataAvvioPrevista: '2025-02-01'
            dataFine: '2025-06-30'
            dataAssegnazione: '2025-03-01'

    FSL.Api.Domain.Models.Gepi.ConsultazioneDettaglioPaiS.Impegno:
      type: object
      properties:
        tipologia:
          type: string
        dataAvvio:
          type: string
          nullable: true
        datafine:
          type: string
          nullable: true
        nucleo:
          type: array
          items:
            type: string
        obiettivoRisultati:
          $ref: '#/components/schemas/FSL.Api.Domain.Models.Gepi.ConsultazioneDettaglioPaiS.ObiettivoRisultato'
      additionalProperties: false
      x-jsonld-type: https://w3id.org/italia/labour-social-policies/onto/social/ImpegnoPaIS
      x-jsonld-context:
        "@vocab": https://w3id.org/italia/labour-social-policies/onto/social/
        tipologia: tipologiaImpegnoPaIS
        dataAvvio: dataAvvioImpegno
        datafine: dataFineImpegno
        nucleo:
          '@id': https://w3id.org/italia/onto/CPV/taxCode
        obiettivoRisultati:
          '@id': haObiettivoPaIS
      example:
        tipologia: 'Tipologia Test'
        dataAvvio: '2025-01-01'
        datafine: '2025-06-30'
        nucleo:
          - 'AAAAAA00A00A000A'


    FSL.Api.Domain.Models.Gepi.ConsultazioneDettaglioPaiS.ObiettivoRisultato:
      type: object
      properties:
        descrizioneObiettivo:
          type: string
        idObiettivo:
          type: string
        risultatiAttesi:
          type: array
          items:
            $ref: '#/components/schemas/FSL.Api.Domain.Models.Gepi.ConsultazioneDettaglioPaiS.RisultatoAtteso'
      additionalProperties: false
      x-jsonld-type: https://w3id.org/italia/labour-social-policies/onto/social/ObiettivoPaIS
      x-jsonld-context:
        "@vocab": https://w3id.org/italia/labour-social-policies/onto/social/
        descrizioneObiettivo: descrizioneObiettivo
        idObiettivo: idObiettivo
        risultatiAttesi:
          '@id': haEsitoRisultatoAttesoObiettivoPaIS
      example:
        descrizioneObiettivo: 'Sostenere l’educazione e la formazione degli adulti'
        idObiettivo: 'ba16de1c-f5a0-4144-90d5-15c354e9eff3'
        risultatiAttesi:
          - descrizioneRisultato: 'Conseguire l’obbligo scolastico'
            idRisultato: '2265d470-4ebd-414b-a77c-59c7cd4fa1da'

    FSL.Api.Domain.Models.Gepi.ConsultazioneDettaglioPaiS.RisultatoAtteso:
      type: object
      properties:
        descrizioneRisultato:
          type: string
        idRisultato:
          type: string
      additionalProperties: false
      x-jsonld-type: https://w3id.org/italia/labour-social-policies/onto/social/RisultatoAttesoDiObiettivo
      x-jsonld-context:
        "@vocab": https://w3id.org/italia/labour-social-policies/onto/social/
        descrizioneRisultato: descrizioneRisultatoAttesoObiettivo
        idRisultato: idRisultatoAttesoObiettivo
      example:
        descrizioneRisultato: 'Conseguire l’obbligo scolastico'
        idRisultato: '2265d470-4ebd-414b-a77c-59c7cd4fa1da'

    FSL.Api.Domain.Models.Gepi.ConsultazioneDettaglioPaiS.Sostegno:
      type: object
      properties:
        tipologia:
          type: string
        idTipologia:
          type: string
        codiceFiscale:
          type: string
        dataAvvio:
          type: string
          nullable: true
        dataAvvioPrevista:
          type: string
          nullable: true
        dataFine:
          type: string
          nullable: true
        dataAssegnazione:
          type: string
          nullable: true
      additionalProperties: false
      x-jsonld-type: https://w3id.org/italia/labour-social-policies/onto/social/SostegnoPaIS
      x-jsonld-context:
        "@vocab": https://w3id.org/italia/labour-social-policies/onto/social/
        tipologia: descrizioneTipologiaSostegnoPaIS
        idTipologia: idTipologiaSostegnoPaIS
        codiceFiscale: https://w3id.org/italia/onto/CPV/taxCode
        dataAvvio: dataAvvioSostegno
        dataAvvioPrevista: dataPrevistaAvvioSostegno
        dataFine: dataFineSostegno
        dataAssegnazione: dataAssegnazioneSostegno
      example:
        tipologia: 'Formazione per il conseguimento di Qualifiche professionali'
        idTipologia: 'bcc888fd-00c7-43ef-8edb-e2bc9b147d17'
        codiceFiscale: 'AAAAAA00A00A000A'
        dataAvvio: '2025-01-01'
        dataAvvioPrevista: '2025-02-01'
        dataFine: '2025-06-30'
        dataAssegnazione: '2025-03-01'

    FSL.Api.Domain.Models.Gepi.Esito:
      required:
        - codiceEsito
        - descrizioneEsito
      type: object
      properties:
        codiceEsito:
          minLength: 1
          type: string
        descrizioneEsito:
          minLength: 1
          type: string
      additionalProperties: false
    FSL.Common.Support.Models.Api.HealthCheckSuccess:
      type: object
      properties:
        status:
          type: string
        totalDuration:
          type: string
        entries: {}
        title:
          type: string
          nullable: true
        detail:
          type: string
          nullable: true
      additionalProperties: false
    Microsoft.AspNetCore.Mvc.ProblemDetails:
      type: object
      properties:
        type:
          type: string
          nullable: true
        title:
          type: string
          nullable: true
        status:
          type: integer
          format: int32
          nullable: true
        detail:
          type: string
          nullable: true
        instance:
          type: string
          nullable: true
      additionalProperties: {}
tags:
  - name: Gepi
    description: Gepi
  - name: Health Check API
    description: Health Check API